# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/Stable.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(679, 442)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.repeat_times_combo = QtWidgets.QComboBox(Form)
        self.repeat_times_combo.setObjectName("repeat_times_combo")
        self.repeat_times_combo.addItem("")
        self.repeat_times_combo.addItem("")
        self.repeat_times_combo.addItem("")
        self.horizontalLayout.addWidget(self.repeat_times_combo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.log_edit = QtWidgets.QTextEdit(Form)
        self.log_edit.setObjectName("log_edit")
        self.verticalLayout.addWidget(self.log_edit)
        self.start_btn = QtWidgets.QPushButton(Form)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(Form)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout.addWidget(self.stop_btn)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Repeat Times:"))
        self.repeat_times_combo.setItemText(0, _translate("Form", "3"))
        self.repeat_times_combo.setItemText(1, _translate("Form", "5"))
        self.repeat_times_combo.setItemText(2, _translate("Form", "10"))
        self.start_btn.setText(_translate("Form", "Start"))
        self.stop_btn.setText(_translate("Form", "Stop"))
